/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.unicahiccpmp.rectorias;
import com.unicahiccpmp.dao.Rector;
import com.unicahiccpmp.dao.RectorModel;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.awt.event.WindowEvent;
/**
 *
 * @author josem
 */
public class RectorForm extends javax.swing.JDialog {

    private Rector currentRector;
    private boolean _reloadParent = false;
    private String _mode;
    
    public boolean getReloadParent(){
        return _reloadParent;
    }
    /**
     * Creates new form RectorForm
     */
    public RectorForm(String Mode, double id) {
        initComponents();
        setModal(true);
        Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
        this.setLocation(dim.width/2-this.getSize().width/2, dim.height/2-this.getSize().height/2);
        
        
        // INS, UPD, DEL, DSP
        _mode = Mode;
        if (!Mode.equals("INS")){
            //No es un insert por tando debe existir en la DB
            //Proceso para capturar el Registro
            System.out.println(id);
            currentRector = RectorModel.getRectoresById(id);
            jTNombres.setText(currentRector.getNOMBRES());
            jTApellidos.setText(currentRector.getAPELLIDOS());
            jTIdentidad.setText(currentRector.getIDENTIDAD());
            jTTelefono.setText(currentRector.getTELEFONO());
            jTCorreo.setText(currentRector.getCORREO());
            jTFchNacimiento.setText(currentRector.getFCHNAC());
            jCGenero.setSelectedItem(currentRector.getGENERO());
            jCUni.setSelectedItem(currentRector.getUNIVERSIDAD());  
        }
        else {
            currentRector = new Rector();
        }
        
        switch(Mode){
            case "INS":
                jLTitle.setText("Agregando nuevo Rector");
                JBConfirmar.setText("Agregar");
                break;
            case "UPD":
                jLTitle.setText(String.format("Actualizando Rector %.0f %s", currentRector.getID(), currentRector.getNOMBRECOMPLETO()));
                JBConfirmar.setText("Editar");
                break;
            case "DEL":
                jLTitle.setText(String.format("Eliminar Rector %.0f %s", currentRector.getID(), currentRector.getNOMBRECOMPLETO()));
                deshabilitarCampos();
                JBConfirmar.setText("Eliminar");
                break;
            case "DSP":
                JBConfirmar.setVisible(false);
                JBCancel.setText("Salir");
                deshabilitarCampos();
                jLTitle.setText(String.format("Rector %.0f %s", currentRector.getID(), currentRector.getNOMBRECOMPLETO()));
                break;
        }
        
    }
    private void deshabilitarCampos(){
         jTNombres.setEditable(false);
         jTApellidos.setEditable(false);
         jTIdentidad.setEditable(false);
         jTTelefono.setEditable(false);
         jTCorreo.setEditable(false);
         jTFchNacimiento.setEditable(false);
         jCGenero.setEditable(false);
         jCUni.setEditable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLTitle = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTNombres = new javax.swing.JTextField();
        jTApellidos = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTIdentidad = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jTTelefono = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jTCorreo = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jCGenero = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        jTFchNacimiento = new javax.swing.JTextField();
        JBConfirmar = new javax.swing.JButton();
        JBCancel = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jCUni = new javax.swing.JComboBox<>();

        setSize(new java.awt.Dimension(600, 500));
        setType(java.awt.Window.Type.POPUP);

        jLTitle.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        jLTitle.setText("Rectores");

        jLabel2.setText("Nombres");

        jLabel3.setText("Apellidos");

        jLabel4.setText("Identidad");

        jLabel5.setText("Teléfono");

        jLabel6.setText("Correo");

        jLabel7.setText("Género");
        jLabel7.setMaximumSize(new java.awt.Dimension(59, 16));
        jLabel7.setMinimumSize(new java.awt.Dimension(59, 16));
        jLabel7.setPreferredSize(new java.awt.Dimension(59, 16));

        jCGenero.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Femenino", "Masculino" }));
        jCGenero.setMinimumSize(new java.awt.Dimension(10, 26));
        jCGenero.setPreferredSize(new java.awt.Dimension(10, 26));

        jLabel8.setText("Nacimiento (YYYY-MM-DD)");

        jTFchNacimiento.setToolTipText("YYYY-MM-DD");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLTitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(394, 394, 394))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jCGenero, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(35, 35, 35)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jTFchNacimiento, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jTIdentidad, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jTCorreo, javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jTTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jTNombres, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(27, 27, 27)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel5)
                                            .addComponent(jTApellidos, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLTitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTNombres, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTApellidos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTIdentidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCGenero, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTFchNacimiento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        JBConfirmar.setText("Agregar");
        JBConfirmar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JBConfirmarMouseClicked(evt);
            }
        });
        JBConfirmar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBConfirmarActionPerformed(evt);
            }
        });

        JBCancel.setText("Cancelar");
        JBCancel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JBCancelMouseClicked(evt);
            }
        });
        JBCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBCancelActionPerformed(evt);
            }
        });

        jLabel9.setText("Universidad");
        jLabel9.setMaximumSize(new java.awt.Dimension(59, 16));
        jLabel9.setMinimumSize(new java.awt.Dimension(59, 16));
        jLabel9.setPreferredSize(new java.awt.Dimension(59, 16));

        jCUni.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "UNICAH", "UNITEC", "UNAH", "UMH", "UNAG", "UTH" }));
        jCUni.setMinimumSize(new java.awt.Dimension(120, 27));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jCUni, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(JBConfirmar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(JBCancel)
                                .addGap(43, 43, 43)))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jCUni, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JBConfirmar)
                    .addComponent(JBCancel))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void JBCancelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JBCancelMouseClicked
        // TODO add your handling code here:
        _reloadParent = false;
        dispatchEvent(new WindowEvent(this, WindowEvent.WINDOW_CLOSING));
    }//GEN-LAST:event_JBCancelMouseClicked

    private void JBConfirmarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JBConfirmarMouseClicked
        // TODO add your handling code here:
        currentRector.setNOMBRES(jTNombres.getText());
        currentRector.setAPELLIDOS(jTApellidos.getText());
        currentRector.setIDENTIDAD(jTIdentidad.getText());
        currentRector.setTELEFONO(jTTelefono.getText());
        currentRector.setCORREO(jTCorreo.getText());
        currentRector.setFCHNAC(jTFchNacimiento.getText());
        currentRector.setUNIVERSIDAD(jCUni.getSelectedItem().toString());
        currentRector.setGENERO(jCGenero.getSelectedItem().toString());
        
        switch(_mode){
            case "INS":
            _reloadParent = RectorModel.agregarrector(currentRector);
            break;
            case "UPD":
            _reloadParent = RectorModel.editarrector(currentRector);
            break;
            case "DEL":
            _reloadParent = RectorModel.eliminarrector(currentRector);
            break;
        }
        dispatchEvent(new WindowEvent(this, WindowEvent.WINDOW_CLOSING));
    }//GEN-LAST:event_JBConfirmarMouseClicked

    private void JBCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBCancelActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_JBCancelActionPerformed

    private void JBConfirmarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBConfirmarActionPerformed
        // TODO add your handling code here:
        //Extrer la informacion
        
       

        //Validaciones Expresiones Regulares

        
    }//GEN-LAST:event_JBConfirmarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton JBCancel;
    private javax.swing.JButton JBConfirmar;
    private javax.swing.JComboBox<String> jCGenero;
    private javax.swing.JComboBox<String> jCUni;
    private javax.swing.JLabel jLTitle;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTApellidos;
    private javax.swing.JTextField jTCorreo;
    private javax.swing.JTextField jTFchNacimiento;
    private javax.swing.JTextField jTIdentidad;
    private javax.swing.JTextField jTNombres;
    private javax.swing.JTextField jTTelefono;
    // End of variables declaration//GEN-END:variables

}
